site_name: benchmark-tool
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - python
repo_url: https://github.com/daajoe/benchmark-tool/
nav:
  - installation.md
  - quickstart.md
  - resultparser.md
  - jobs.md
  - instance-specs.md
  - export-import.md
markdown_extensions:
  - toc:
      permalink: True
  - admonition
